---
# tasks file for ansible-role-hosts-file

- name: Add line to hosts file
  lineinfile: dest=/etc/hosts state=present  line="{{ item }}"
  with_items: hosts_file.add
  when: hosts_file.add is defined

- name: Add line to hosts file
  lineinfile: dest=/etc/hosts state=absent  regexp="{{ item }}"
  with_items: hosts_file.remove
  when: hosts_file.remove is defined
